tes/tes/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # Main app
    path('', include('tesapp.urls')),
    # Auth app
    path('users/', include('users.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tes/tesapp/urls.py
from django.urls import path

from .views import (
    PhotoListView,
    PhotoTagListView,
    PhotoDetailView,
    PhotoCreateView,
    PhotoUpdateView,
    PhotoDeleteView,
    homeview,
    FileListView,
    subscribe_view,
    
)
from tesapp import views


app_name = 'photo'

urlpatterns = [
    path('', homeview, name='home'),
    path('photo/list/', PhotoListView.as_view(), name='list'),
    path('photo/articles/', FileListView.as_view(), name='article'),

    path('tag/<slug:tag>/', PhotoTagListView.as_view(), name='tag'),

    path('photo/<int:pk>/', PhotoDetailView.as_view(), name='detail'),

    path('photo/create/', PhotoCreateView.as_view(), name='create'),

    path('photo/<int:pk>/update/', PhotoUpdateView.as_view(), name='update'),

    path('photo/<int:pk>/delete/', PhotoDeleteView.as_view(), name='delete'),
    # path('success/', views.success_view, name='success_page'),
    # path('subscribe/', views.subscribe_view, name='subscribe_view'),

    # path('subscribe_page/', views.subscribe_page , name='subscribe'),
    



    path('contact/', views.contact_view , name='contact'),
    path('subscribe/', views.subscribe_view , name='subscribe'),







]

tes/tesapp/models.py
from django.db import models
import uuid,os

# Create your models here.
from django.db import models

from django.contrib.auth import get_user_model

from taggit.managers import TaggableManager

from django.utils import timezone

def generate_upload_path(instance, filename):
     # Generate a unique filename for the uploaded file
     filename = f'{uuid.uuid4()}{os.path.splitext(filename)[1]}'
     # Return the upload path
     return f'photos/{filename}'

class Photo(models.Model):
    title = models.CharField(max_length=45)
    description = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='photos/')
    submitter = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    tags = TaggableManager()

    def __str__(self):
        return self.title


class File(models.Model):
    file_title = models.CharField(max_length=45)
    file_author = models.CharField(max_length=45)
    file_description = models.CharField(max_length=250)
    file_thumbnail = models.ImageField(upload_to='file_image/', default='default_thumbnail.jpg')
    file_created = models.DateTimeField(auto_now_add=True)
    file = models.FileField(upload_to='files/')
    file_submitter = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    sas_url = models.URLField(blank=True)

    def __str__(self):
        return self.file_title
from django.db import models

class Subscriber(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email


class contact(models.Model):
    name = models.CharField( max_length=50)
    message = models.CharField( max_length=500)

    def __str__(self):
        return self.name

tes/tesapp/forms.py
from django import forms
from .models import Photo,File,Subscriber

class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['title', 'description', 'image', 'tags']

class FileForm(forms.ModelForm):
    class Meta:
        model = File
        fields = ['file_title', 'file_author', 'file_description', 'file_thumbnail']
from django.db import models

from django import forms
from .models import Subscriber

class SubscriberForm(forms.Form):
    name = forms.CharField(max_length=100)
    roll_no = forms.CharField(max_length=10)
    email = forms.EmailField(max_length=254)

from django import forms
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)

tes/tesapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
from django.shortcuts import get_object_or_404

from django.core.exceptions import PermissionDenied

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from django.urls import reverse_lazy

from .models import Photo,File,contact

from django.shortcuts import render


class PhotoListView(ListView):

    model = Photo     

    template_name = 'tesapp/list.html'

    context_object_name = 'photos'

from django.views.generic import ListView
from .models import File

class FileListView(ListView):
    model = File
    template_name = 'tesapp/articles.html'
    context_object_name = 'files'


class PhotoTagListView(PhotoListView):

    template_name = 'tesapp/taglist.html'

    # Custom method
    def get_tag(self):
        return self.kwargs.get('tag')

    def get_queryset(self):
        return self.model.objects.filter(tags__slug=self.get_tag())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tag"] = self.get_tag()
        return context

# photoapp/views.py



class PhotoDetailView(DetailView):

    model = Photo

    template_name = 'tesapp/detail.html'

    context_object_name = 'photo'




class PhotoCreateView(LoginRequiredMixin, CreateView):

    model = Photo

    fields = ['title', 'description', 'image', 'tags']

    template_name = 'tesapp/create.html'

    success_url = reverse_lazy('photo:list')

    def form_valid(self, form):

        form.instance.submitter = self.request.user

        return super().form_valid(form)


class UserIsSubmitter(UserPassesTestMixin):

    # Custom method
    def get_photo(self):
        return get_object_or_404(Photo, pk=self.kwargs.get('pk'))

    def test_func(self):

        if self.request.user.is_authenticated:
            return self.request.user == self.get_photo().submitter
        else:
            raise PermissionDenied('Sorry you are not allowed here')


class PhotoUpdateView(UserIsSubmitter, UpdateView):

    template_name = 'tesapp/update.html'

    model = Photo

    fields = ['title', 'description', 'tags']

    success_url = reverse_lazy('photo:list')

class PhotoDeleteView(UserIsSubmitter, DeleteView):

    template_name = 'tesapp/delete.html'

    model = Photo

    success_url = reverse_lazy('photo:list')  

from django.shortcuts import render
from .models import Photo

def homeview(request):
    # Retrieve all Photo objects
    photos = Photo.objects.all()
    files = File.objects.all()
    context = {'photos': photos, 'files': files}


    return render(request, 'tesapp/home.html' , context)







from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import ContactForm,SubscriberForm  # Import the ContactForm class from forms.py

from .models import contact

def contact_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            message = form.cleaned_data['message']
            
            # Save the data into the database
            new_contact = contact(name=name, message=message)
            new_contact.save()

            # Assuming you have sent a success message, you can use it like this:
            success_message = "Thank you for your message!"
            return render(request, 'tesapp/home.html', {'success_message': success_message})
    else:
        form = ContactForm()

    return render(request, 'tesapp/home.html', {'form': form})


from django.http import JsonResponse
from .models import Subscriber

def subscribe_view(request):
    if request.method == 'POST':
        email = request.POST.get('email')  # Get the email from the form
        subscriber = Subscriber(email=email)
        subscriber.save()
        return JsonResponse({'message': 'Subscription successful'})

    return render(request, 'subscribe.html')  # Render the form initially





'tesapp/list.html' 
'tesapp/subscribe.html' 
'tesapp/home.html' 
'tesapp/articles.html' 
'tesapp/taglist.html' 
'tesapp/detail.html' 
'tesapp/create.html' 
'tesapp/update.html' 
'tesapp/delete.html'
'tesapp/success.html'

tes/tesapp/templates/tesapp/articles.html
{% extends 'base.html' %}
{% block title %}Article's and Magazines {% endblock title %}

{% block body %}
<div class="px-4 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8">
  
  <div class="container py-5">
    <div class="text-center text-700  wow fadeInUp" data-wow-delay="0.1s">
      <h6 class="text-secondary text-uppercase">Our Readings</h6>
      <h1 class="mb-5" style = "font-size: calc(1.375rem + 1.5vw)!important; ">MAGAZINES & ARTICLE'S</h1>
  </div>

  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mx-auto">
    {% for file in files %}
    <div class="p-6">
      <a href="{{ file.file.url }}" class="">

      <img class="object-cover object-center w-full mb-8 lg:h-56 md:h-56 rounded-xl" src="{{file.file_thumbnail.url}}" alt="blog">
      </a>
      <div class="inline-flex justify-between w-full">
        <h1 class="mb-8 text-xl font-semibold leading-none tracking-tighter text-neutral-600">{{file.file_title}}</h1>
        <span>{{file.file_created}}</span>
      </div>
      <p class="mx-auto text-base font-medium leading-relaxed text-gray-500 truncate-overflow">
        {{ file.file_description|truncatewords:15 }}
      </p>
    </div>
    {% endfor %}
  </div>
  
</div>


{% endblock body %}

tes/tesapp/templates/tesapp/create.html
{% extends 'base.html' %} 

{% block body %}
{% load static %}


<h1 class="mb-4 py-24  text-3xl text-center font-extrabold leading-none tracking-tight text-gray-900 md:text-3xl lg:text-3xl ">Dear <mark class="px-2 text-white bg-blue-600 rounded dark:bg-blue-500">{{user.username}}</mark> upload your post</h1>
<div class="flex mx-40  justify-between">

<form class="mx-5 my-8" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  
   
      <div class="mb-2">
        <label for="{{ form.title.id_for_label }}" class="block text-gray-700 font-medium mb-2">Title:</label>
        {{ form.title }}
      </div>
  
      <div class="mb-2">
        <label for="{{ form.description.id_for_label }}" class="block text-gray-700 font-medium mb-2">Description:</label>
        {{ form.description }}
      </div>
 
  
    
      <div class="mb-2">
        <label for="{{ form.tags.id_for_label }}" class="block text-gray-700 font-medium mb-2">Tags:</label>
        {{ form.tags }}
      </div>
  
      <div class="mb-2">
        <label for="{{ form.image.id_for_label }}" class="block text-gray-700 font-medium mb-2">Image:</label>
        {{ form.image }}
      </div>
    
  
  

  <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
    Submit
 </button>

 {% comment %}  for MAGAZINES&something  {% endcomment %}
</form>
  


<div>
<img class="h-auto max-w-lg transition-all duration-300 rounded-lg " src="{% static 'images/Screenshot 2023-06-22 230740.png' %}" alt="image description">

</div>

</div>



{% endblock body %}

tes/tesapp/templates/tesapp/delete.html
{% extends 'base.html' %} 

{% block body %}
<div class="form-group mx-auto">
  <h2 class="text-center">
    You are going to <span class="text-danger">delete</span>: "<i
      >{{ photo }}</i
    >
    "
  </h2>
  <p class="text-center">Are you sure, you want to delete the photo ?</p>
  <div class="form-group">
    <form
      action=""
      method="post"
      class="d-flex flex-column align-items-center justify-content-center"
    >
      {% csrf_token %}
      <div class="row">
        <div class="col">
          <a href="{% url 'photo:detail' photo.id %}" class="btn btn-primary"
            >Cancel</a
          >
        </div>
        <div class="col">
          <button type="submit" class="btn btn-danger">Delete</button>
        </div>
      </div>
      <p>This action is irreversible</p>
    </form>
  </div>
</div>

{% endblock body %}

tes/tesapp/templates/tesapp/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="mx-auto">
  
<h1 class="mb-4 pt-40 text-center text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xl dark:text-white"><span class="text-blue-600 dark:text-blue-500">{{ photo.title }}</span> </h1>


  {% comment %} <p class="text-center font-light">
    Uploaded on: {{ photo.created }}<br />
  </p> {% endcomment %}
  {% if user == photo.submitter %}
  <p class="text-center">
    <a href="{% url 'photo:update' photo.id %}" class="text-primary px-2"
      >Update</a
    >
    <a href="{% url 'photo:delete' photo.id %}" class="text-danger px-2"
      >Delete</a
    >
  </p>
  {% endif %}
</div>

















<div class="px-4 py-16 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8 lg:py-20">
  <div class="grid gap-10 lg:grid-cols-2">
    <div class="lg:pr-10">
     
      <h5 class="mb-4 text-4xl font-extrabold leading-none">
        {{ photo.title }}
      </h5>
      <p class="mb-6 text-gray-900">
        {{ photo.description }}
      </p>
      <hr class="mb-5 border-gray-300" />
      Uploaded on: {{ photo.created }}
    </div>
    <div>
      <img class="object-cover w-full h-56 rounded shadow-lg sm:h-96" src="{{ photo.image.url }}" alt="" />
    </div>
  </div>
</div>

{% endblock body %}

tes/tesapp/templates/tesapp/list.html
{% extends 'base.html' %}
{% block title %}All events {% endblock title %}

{% block body %}

    <!-- Page Header Start -->
    <div class="container-fluid page-header py-5" style="margin-bottom: 6rem;">
      <div class="container py-5">
          <h1 class="display-3 text-white mb-3 animated slideInDown">Events</h1>
          <nav aria-label="breadcrumb animated slideInDown">
              <ol class="breadcrumb">
                  <li class="breadcrumb-item"><a class="text-white" href="/">Home</a></li>
                  <li class="breadcrumb-item"><a class="text-white" href="#">Pages</a></li>
                  <li class="breadcrumb-item text-white active" aria-current="#">Events</li>
              </ol>
          </nav>
      </div>
  </div>
  <!-- Page Header End -->

    <!-- Service Start -->
    <div id = "Events" class="container-xxl py-5">
      <div class="container py-5">
        <div class="text-center text-700  wow fadeInUp" data-wow-delay="0.1s">
          <h6 class="text-secondary text-uppercase">Our Events</h6>
          <h1 class="mb-5" style = "    font-size: calc(1.375rem + 1.5vw)!important; ">Explore Our Events</h1>
      </div>
          <div class="row g-4">
            {% for photo in photos %}

              <div class="col-md-6 col-lg-4 wow fadeInUp" data-wow-delay="0.3s">
                  <div class="service-item p-4">
                      <div class="overflow-hidden mb-4">
                          <img class="img-fluid" src="{% if photo.image %}{{ photo.image.url }}{% else %}{% endif %}" alt="">
                      </div>
                      <h4 class="mb-3">{{ photo.title }}</h4>
                      <p>{{ photo.description|truncatewords:15 }}</p>
                      <a class="btn-slide mt-2" href="{% url 'photo:detail' photo.id %}" ><i class="fa fa-arrow-right"></i><span>Read More</span></a>
                  </div>
              </div>
              {% endfor %}
          </div>
      </div>
  </div>
  <!-- Service End -->
{% endblock body %}

tes/tesapp/templates/tesapp/subscribe.html
{% extends 'base.html' %}
{% block body %}


<div class=" py-20 relative">
  <img src="https://images.unsplash.com/photo-1611743503489-09f50e0be8e4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1859&q=80" class="absolute inset-0 object-cover w-full h-full" alt="" />
  <div class="relative bg-gray-900 bg-opacity-75">
    <div class="px-4 py-16 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8 lg:py-20">
      <div class="flex flex-col items-center justify-between xl:flex-row">
        <div class="w-full max-w-xl mb-12 xl:mb-0 xl:pr-16 xl:w-7/12">
          <h2 class="max-w-lg mb-6 font-sans text-3xl font-bold tracking-tight text-white sm:text-4xl sm:leading-none">
            The quick, brown fox <br class="hidden md:block" />
            jumps over a <span class="text-teal-accent-400">lazy dog</span>
          </h2>
          <p class="max-w-xl mb-4 text-base text-gray-400 md:text-lg">
            Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudan, totam rem aperiam, eaque ipsa quae.
          </p>
          <a href="/" aria-label="" class="inline-flex items-center font-semibold tracking-wider transition-colors duration-200 text-teal-accent-400 hover:text-teal-accent-700">
            Learn more
            <svg class="inline-block w-3 ml-2" fill="currentColor" viewBox="0 0 12 12">
              <path d="M9.707,5.293l-5-5A1,1,0,0,0,3.293,1.707L7.586,6,3.293,10.293a1,1,0,1,0,1.414,1.414l5-5A1,1,0,0,0,9.707,5.293Z"></path>
            </svg>
          </a>
        </div>
        <div class="w-full max-w-xl xl:px-8 xl:w-5/12">
          <div class="bg-white rounded shadow-2xl p-7 sm:p-10">
            <h3 class="mb-4 text-xl font-semibold sm:text-center sm:mb-6 sm:text-2xl">
              Subscribe for Regular Updates
            </h3>
            <form method="post" action="{% url 'photo:subscribe' %}" >

              {% csrf_token %}
              <div class="mb-1 sm:mb-2">
                <label for="Name" class="inline-block mb-1 font-medium">Name</label>
                <input
                  placeholder="John"
                  required=""
                  type="text"
                  class="flex-grow w-full h-12 px-4 mb-2 transition duration-200 bg-white border border-gray-300 rounded shadow-sm appearance-none focus:border-deep-purple-accent-400 focus:outline-none focus:shadow-outline"
                  id="name"
                  name="name"
                />
              </div>
              <div class="mb-1 sm:mb-2">
                <label for="roll no" class="inline-block mb-1 font-medium">Roll No</label>
                <input
                  placeholder="21XX1XXX1"
                  required=""
                  type="text"
                  class="flex-grow w-full h-12 px-4 mb-2 transition duration-200 bg-white border border-gray-300 rounded shadow-sm appearance-none focus:border-deep-purple-accent-400 focus:outline-none focus:shadow-outline"
                  id="roll_no"
                  name="roll_no"
                />
              </div>
              <div class="mb-1 sm:mb-2">
                <label for="email" class="inline-block mb-1 font-medium">E-mail</label>
                <input
                  placeholder="john.doe@example.org"
                  required=""
                  type="text"
                  class="flex-grow w-full h-12 px-4 mb-2 transition duration-200 bg-white border border-gray-300 rounded shadow-sm appearance-none focus:border-deep-purple-accent-400 focus:outline-none focus:shadow-outline"
                  id="email"
                  name="email"
                />
              </div>
              <div class="mt-4 mb-2 sm:mb-4">
                <button
                  type="submit"
                  class="inline-flex items-center justify-center w-full h-12 px-6 font-medium tracking-wide text-black transition duration-200 rounded shadow-md bg-blue-400 hover:bg-blue-700 focus:shadow-outline focus:outline-none"
                >
                  Subscribe
                </button>
              </div>


              
              
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock body %}

tes/tesapp/templates/tesapp/success_template.html
<h1>Success</h1>

tes/tesapp/templates/tesapp/taglist.html
{% extends 'photoapp/list.html' %}

{% block body %}

<div class="alert alert-primary">
    <h2 class="text-center">Photos with the tag {{tag}}</h2>
</div>

{{ block.super }}

{% endblock body %}

tes/tesapp/templates/tesapp/update.html
{% extends 'base.html' %}

{% block body %}
<div class="mx-auto">
  <h1 class="mt-3 text-center">Edit photo {{photo}}</h1>
</div>
<div class="form-group">
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <button type="submit" class="btn btn-success mb-3">Edit Photo</button>
  </form>
</div>
{% endblock body %}