tes/tes/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # Main app
    path('', include('tesapp.urls')),
    # Auth app
    path('users/', include('users.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tes/tesapp/urls.py
from django.urls import path

from .views import (
    PhotoListView,
    PhotoTagListView,
    PhotoDetailView,
    PhotoCreateView,
    PhotoUpdateView,
    PhotoDeleteView,
    homeview,
    FileListView,
    subscribe_view,
    
)
from tesapp import views


app_name = 'photo'

urlpatterns = [
    path('', homeview, name='home'),
    path('photo/list/', PhotoListView.as_view(), name='list'),
    path('photo/articles/', FileListView.as_view(), name='article'),

    path('tag/<slug:tag>/', PhotoTagListView.as_view(), name='tag'),

    path('photo/<int:pk>/', PhotoDetailView.as_view(), name='detail'),

    path('photo/create/', PhotoCreateView.as_view(), name='create'),

    path('photo/<int:pk>/update/', PhotoUpdateView.as_view(), name='update'),

    path('photo/<int:pk>/delete/', PhotoDeleteView.as_view(), name='delete'),
    # path('success/', views.success_view, name='success_page'),
    # path('subscribe/', views.subscribe_view, name='subscribe_view'),

    # path('subscribe_page/', views.subscribe_page , name='subscribe'),
    



    path('contact/', views.contact_view , name='contact'),
    path('subscribe/', views.subscribe_view , name='subscribe'),







]

tes/templates/base.html
{% load compress %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="icon" type="image/x-icon" href="{% static 'tesd.png' %}">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock title %}| TES</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://unpkg.com/tailwindcss-jit-cdn"></script>
    <link rel="stylesheet" href="{{ STATIC_URL }}base.css" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.4/flowbite.min.js"></script>
    <script src="https://cdn.tailwindcss.com"></script>

        <!-- Google Web Fonts -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&family=Roboto:wght@500;700&display=swap" rel="stylesheet">

        <!-- Icon Font Stylesheet -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    
        <!-- Libraries Stylesheet -->
        <link href="lib/animate/animate.min.css" rel="stylesheet">
        <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    
        <!-- Customized Bootstrap Stylesheet -->
        <link href="css/bootstrap.min.css" rel="stylesheet">
    
        <!-- Template Stylesheet -->
        <link href="css/style.css" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'src/output.css' %}">

    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">







</head>
 
<style>
    
</style>

<nav> {% include 'navbar.html' %} </nav>


  


<body>{% block body %}
        
    {% endblock body %}
</body>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>


<script src="{% static 'lib/wow/wow.min.js' %}" ></script>
<script src="{% static 'lib/easing/easing.min.js' %}" ></script>
<script src="{% static 'lib/waypoints/waypoints.min.js' %}" ></script>
<script src="{% static 'lib/counterup/counterup.min.js' %}" ></script>
<script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}" ></script>
<script src="{% static 'js/main.js' %}" ></script>
 

</html>

tes/templates/navbar.html
{% load static %}
<style>
  .collapse{
    visibility: visible;
  }
</style>



    <!-- Navbar Start -->
    <nav class="navbar navbar-expand-lg bg-white navbar-light shadow border-top border-5 sticky-top p-0">
        <a href="/" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
            {% comment %} <h2 class="mb-2 text-white">Logistica</h2> {% endcomment %}
            <img src="{% static 'tesd.png' %}"class="flex title-font font-medium items-center" alt="logo" width="45" height="45">

        </a>
        <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto p-4 p-lg-0">
                <a href="/" class="nav-item nav-link active">Home</a>
                <a href="{% url 'photo:list' %}" class="nav-item nav-link">Events</a>
                <a href="{% url 'photo:article' %}" class="nav-item nav-link">Articles</a>
                <a href="/#team-section" class="nav-item nav-link">Team</a>
                <a href="/#contact" class="nav-item nav-link">Contact</a>
            </div>
            
            {% if user.is_authenticated %}
              <button type="button" class=" btn btn-secondary py-md-3 px-md-5 me-3 animated slideInLeft">
              <a class="text-black" href="{% url 'photo:create' %}">Add a photo</a>
              </button>
            {% endif %}
        </div>
    </nav>
    <!-- Navbar End -->